ALTER TABLE Categoria DROP CONSTRAINT FKCategoria441513;
ALTER TABLE Presupuesto DROP CONSTRAINT crea;
ALTER TABLE Pago DROP CONSTRAINT genera;
ALTER TABLE Cuenta_Bancaria DROP CONSTRAINT posee;
ALTER TABLE Presupuesto DROP CONSTRAINT realiza;
ALTER TABLE Planificacion DROP CONSTRAINT tiene;
DROP TABLE IF EXISTS Categoria CASCADE;
DROP TABLE IF EXISTS Cuenta_Bancaria CASCADE;
DROP TABLE IF EXISTS Pago CASCADE;
DROP TABLE IF EXISTS Planificacion CASCADE;
DROP TABLE IF EXISTS Presupuesto CASCADE;
DROP TABLE IF EXISTS Tarjeta_Credito CASCADE;
DROP TABLE IF EXISTS Usuario CASCADE;

